### ISSUE TITLE
Create a feature branch from staging

### ISSUE THREAD

**Issue by ohjimijimijimi** [ohjimijimijimi/deployment-flow-playground#1]
### TODO
- [x] Create a new feature branch for this issue
- [x] Commit some code and push the branch
- [x] Open a PR with base `develop` and assign a reviewer
- [x] When reviewed, merge the changes
- [x] Wait until QA is finished and when asked to add a new PR with base `staging` and assign a reviewer
- [x] When reviewed, merge the changes to `staging`
- [x] Wait until the `staging` QA phase is completed, then merge `staging` to `master`
