### ISSUE TITLE
Use git flow to develop a new feature

### ISSUE THREAD

**Issue by ohjimijimijimi** [ohjimijimijimi/deployment-flow-playground#6]
### TODO
- [x] Start a new feature (`git flow feature start <context>-<issue>-<description>`)
- [x] Commit some code and push the branch
- [x] Open a PR with base `develop` and assign a reviewer
- [x] When reviewed, merge the changes
- [x] Finish the feature (`git flow feature finish <context>-<issue>-<description>`)
- [ ] Wait until the `staging` QA phase is completed, then make a new release:
    ```
    git flow release start 2.0.0
    git flow release finish
    git push
    git checkout master
    git push && git push --tags
    ```

**Comment by ohjimijimijimi** [comment]
@testingcollaborator I finished to QA this on staging. Let's deploy
